[project]
name = "dingz"
version = "0.6.0.dev0"
authors = [
    { name = "Fabian Affolter", email = "fabian@affolter-engineering.ch" },
    { name = "Simon Berger", email = "simon@siku2.io" },
]
description = "Python API for interacting with Dingz devices"
readme = "README.rst"
license = "Apache-2.0"
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Utilities",
]
dependencies = [
    "aiohttp<4",
    "async-timeout>=5.0.1 ; python_full_version < '3.11'",
    "click>=8.1.8",
    "typing-extensions>=4.14.1",
    "zeroconf>=0.147.0",
]

[project.urls]
Repository = "https://github.com/home-assistant-ecosystem/python-dingz"

[project.scripts]
dingz = "dingz.cli:main"

[build-system]
requires = ["uv_build>=0.8.7,<0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "dingz"
module-root = ""

[dependency-groups]
dev = ["ruff>=0.12.8"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
# See: <https://docs.astral.sh/ruff/rules>
select = ["ALL"]
ignore = [
    "D203",   # Use 'no-blank-line-before-class' instead of 'incorrect-blank-line-before-class'
    "D213",   # Use 'multi-line-summary-second-line' instead of 'multi-line-summary-first-line'
    "COM812", # Formatter already enforces trailing commas
    "S101",   # Allow assert
]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.ruff.lint.per-file-ignores]
"example.py" = [
    "T201", # Allow 'print' in example
]
"cli.py" = [
    "T201", # Allow 'print' in cli
]
